# Generated by Django 5.2.12 on 2026-05-02 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=50)),
                ('fertilizer_name', models.CharField(max_length=100)),
                ('quantity_per_acre', models.CharField(max_length=50)),
                ('when_to_apply', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CropInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('soil_type', models.CharField(choices=[('black', 'Black Soil'), ('red', 'Red Soil'), ('sandy', 'Sandy Soil'), ('loamy', 'Loamy Soil'), ('other', 'Other')], max_length=20)),
                ('ph_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nitrogen', models.CharField(max_length=10)),
                ('phosphorus', models.CharField(max_length=10)),
                ('potassium', models.CharField(max_length=10)),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('summer', 'Summer')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_crop', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('alt_crop_1', models.CharField(blank=True, max_length=100)),
                ('alt_crop_2', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('crop_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='agroapp.cropinput')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(choices=[('kn', 'Kannada'), ('en', 'English'), ('hi', 'Hindi')], default='kn', max_length=5)),
                ('land_size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('black', 'Black Soil'), ('red', 'Red Soil'), ('sandy', 'Sandy Soil'), ('loamy', 'Loamy Soil'), ('other', 'Other')], max_length=20)),
                ('preferred_crops', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
